version: '3'

services:
  database:
    image: 'postgres:16.2'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: herocrafter
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
    volumes:
      - pg-volume:/var/lib/postgresql/data
  cache:
    image: 'redis:8.0-rc1-alpine'
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
  minio:
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=root-user
      - MINIO_ROOT_PASSWORD=root-password
    volumes:
      - minio:/bitnami/minio/data
  server:
    build: .
    platform: linux/amd64
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy



volumes:
  pg-volume: {}
  cache: {}
  minio: {}