version: '3'

services:
  database:
    image: 'postgres:16.2'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: herocrafter
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
    volumes:
      - pg-volume:/var/lib/postgresql/data
  server:
    build: .
    platform: linux/amd64
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy

volumes:
  pg-volume: {}