CREATE TABLE card (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    collectors_number INTEGER,
    format TEXT,
    name TEXT NOT NULL,
    archetype TEXT,
    action_cost INTEGER,
    power_cost INTEGER,
    range INTEGER,
    health INTEGER,
    heroic BOOLEAN NOT NULL,
    slow BOOLEAN NOT NULL,
    silence BOOLEAN NOT NULL,
    disarm BOOLEAN NOT NULL,
    extra_type TEXT,
    rules_text TEXT,
    flavor_text TEXT,
    artist TEXT NOT NULL,
    ivion_uuid uuid NOT NULL,
    color_pip_1 TEXT,
    color_pip_2 TEXT,
    season TEXT NOT NULL,
    type TEXT
)
