name: Release Tagger

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'src/webapp/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get next version
        uses: reecetech/version-increment@2024.10.1
        id: version
        with:
          scheme: calver

      - name: Tag Latest
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "latest"
          tag_exists_error: false
          message: "Latest release"

      - name: Tag Version
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.version.outputs.v-version }}
          message: "Version ${{ steps.version.outputs.version }}"